export const filterData = {
  tutoringStyles: [
    "One to One",
    "One to many",
    "Online Tutoring",
    "Shadow Tutoring ",
  ],
  tuitionType: [
    "Home Tutoring",
    "Online Tutoring",
    "Batch Tutoring",
    "Package Tutoring",
  ],
  daysPerWeek: [
    "1 Day",
    "2 Days",
    "3 Days",
    "4 Days",
    "5 Days",
    "6 Days",
    "7 Days",
  ],
  cityCorporations: [
    "Dhaka",
    "Savar",
    "Chattogram",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
    "Rangpur",
    "Cumilla",
    "Gazipur",
    "Narayanganj",
    "Mymensingh",
  ],
  cityCorporationWithLocation: [
    {
      name: "Dhaka",
      locations: [
        "Abdullahpur",
        "Adabor",
        "Aftabnagar",
        "Agargaon",
        "Airport Area ",
        "Arambagh",
        "Armanitola",
        "Asad Gate ",
        "Ashkona",
        "Azampur Kachabazar",
        "Azimpur",
        "Badda",
        "Baily Road",
        "Bakshi Bazar",
        "Banani",
        "Banani DOHS",
        "Banasree",
        "Bangla Motor",
        "Bangshal",
        "Baridhara",
        "Baridhara DOHS",
        "Bashabo",
        "Bashundhara R/A",
        "Bashundhara Riverview",
        "Baunia",
        "Begun Bari",
        "Bijoy Sarani",
        "Bijoynagar",
        "Bosila",
        "BUET Area",
        "Central Road ",
        "Chandrima Model Town",
        "Chawk Bazar",
        "College Gate",
        "Darussalam",
        "Daskhin Khan",
        "Demra",
        "Dhaka  Cantonment",
        "Dhaka Uddan Housing",
        "Dhaka University Area",
        "Dhanmondi",
        "Dholaikhal",
        "Dholaipar",
        "Diabari",
        "Dilkusha",
        "Dilu Road",
        "Doyagonj",
        "Eastern Housing",
        "ECB Chattar",
        "Elephant Road",
        "English Road",
        "Faidabad",
        "Faridabad",
        "Farmgate",
        "Fokirapul",
        "Gabtoli",
        "Gandaria",
        "Golapbag",
        "Gopibagh",
        "Goran",
        "Green Road",
        "Gulistan",
        "Gulshan-1",
        "Gulshan-2",
        "Hatirjheel",
        "Hatirpul",
        "Hazaribag",
        "Ibrahimpur",
        "Indira Road ",
        "Jatrabari",
        "Joynag Road",
        "Jurain ",
        "Kachukhet",
        "Kadamtoli",
        "Kafrul",
        "Kakrail",
        "Kalabagan",
        "Kalachandpur",
        "Kalshi",
        "Kamalapur",
        "Kamarpara",
        "Kamrangirchar",
        "Karwan Bazar",
        "Katabon",
        "Kathal Bagan",
        "Kawla",
        "Kazipara",
        "Kazla",
        "Keraniganj",
        "Khilgaon",
        "Khilkhet",
        "Kollanpur",
        "Kotwali",
        "Kuril",
        "Kurmitola",
        "Lake Circus Road",
        "Lalbag",
        "Lalmatia",
        "Luxmi Bazar",
        "Malibagh",
        "Manikdi",
        "Maniknagar",
        "Matikata",
        "Matuail",
        "Mirpur 1",
        "Mirpur 10",
        "Mirpur 11",
        "Mirpur 12",
        "Mirpur 13",
        "Mirpur 14",
        "Mirpur 2",
        "Mirpur 3",
        "Mirpur 6",
        "Mirpur 7",
        "Mirpur Cantonment",
        "Mirpur DOHS",
        "Mitford Road",
        "Mogbazar",
        "Mohakhali",
        "Mohakhali DOHS",
        "Mohammadpur",
        "Mollartek",
        "Monipur",
        "Monipuri Para",
        "Motijheel",
        "Mouchak",
        "Mugda",
        "Nakhalpara",
        "Nandipara",
        "Narinda",
        "Natun Bazar",
        "Nawabpur",
        "Naya Bazar",
        "Naya Paltan",
        "New Eskaton Road",
        "New Market",
        "Niketon",
        "Nikunja-1",
        "Nikunja-2",
        "Nilkhet",
        "Nobabgonj ",
        "Norda",
        "Paikpara",
        "Pallabi",
        "Paltan",
        "Panthapath",
        "Paribag",
        "Pilkhana",
        "Pink City Model Town",
        "Pirerbag",
        "Postogola",
        "Puran Dhaka",
        "Purana Paltan",
        "Ramna",
        "Rampura",
        "Ranavola",
        "Rayer Bazar",
        "Rayerbag",
        "Razarbagh",
        "Rupnagar",
        "Sabujbag",
        "Sadarghat",
        "Sankar",
        "Sayedabad",
        "Segunbagicha ",
        "Shahbag",
        "Shahinbag",
        "Shahjadpur",
        "Shajahanpur",
        "Shantibag",
        "Shantinagar",
        "Shekhertek",
        "Sher-e-Bangla Nagor",
        "Shewra",
        "Shewrapara",
        "Shyamoli",
        "Shyampur",
        "Siddeshwari",
        "Sobahan Bag",
        "Sonir Akra",
        "South Banasree",
        "Sukrabad",
        "Sutrapur",
        "Swamibagh",
        "Tejgaon",
        "Tejkunipara",
        "Tikatuli",
        "Tolarbag",
        "Turag",
        "Uttar Khan",
        "Uttara Sector 1",
        "Uttara Sector 10",
        "Uttara Sector 11",
        "Uttara Sector 12",
        "Uttara Sector 13",
        "Uttara Sector 14",
        "Uttara Sector 15",
        "Uttara Sector 16",
        "Uttara Sector 17",
        "Uttara Sector 18",
        "Uttara Sector 2",
        "Uttara Sector 3",
        "Uttara Sector 4",
        "Uttara Sector 5",
        "Uttara Sector 6",
        "Uttara Sector 7",
        "Uttara Sector 8",
        "Uttara Sector 9",
        "Vasantek",
        "Vatara",
        "Wari",
        "West Rampura",
        "Zigatola",
        "Zinzira",
      ],
    },
    {
      name: "Savar",
      locations: [
        "Thana Road",
        "20 Mile",
        "Anondopur",
        "Ashuliya",
        "Baipal",
        "Bank Colony",
        "Bank Town",
        "Bazar Road",
        "BEPZA",
        "Birulia Road",
        "C R P Road",
        "Cantonment",
        "Dendabor",
        "DEPZ",
        "Dhamrai",
        "East Bank Town",
        "Genda",
        "Jahangirnagar University Area",
        "Jamgora",
        "Kolma",
        "Majidpur",
        "Mousumi Market",
        "Nayarhat",
        "Nobinagar",
        "Norosinhopur",
        "Palli Bidyut",
        "Radio Colony",
        "Savar Bus Stand",
        "Savar DOHS",
        "Sobhanbag",
        "Soronika R/A",
        "Wapda Road",
        "West Bank Town",
        "Zirabo",
      ],
    },
    {
      name: "Chattogram",
      locations: [
        " New Mooring",
        "2 No. Gate",
        "A.K Khan",
        "Agrabad",
        "Agrabad Access Road",
        "Agrabad Barek Building",
        "Agrabad CDA R/A",
        "Agrabad Chowmuhani",
        "Akbarshah Railway Colony",
        "Ali Nagar",
        "Alkaran ",
        "Aman Bazar",
        "Amirbag",
        "Amtala",
        "Andarkilla",
        "Arakan H/S",
        "Arefin Nagar ",
        "Ashkar Dighir Par",
        "Aturar Depo",
        "Avay Mitra Ghat",
        "Badurtala",
        "Bahaddarhat",
        "Baitush Sharaf",
        "Bakalia East ",
        "Bakalia South",
        "Bakalia West ",
        "Baluchara",
        "Banani R/A",
        "Bandar",
        "Bangladesh Bank Colony",
        "Batali Road ",
        "Battery Goli",
        "Bayazid Bostami",
        "Bepari Para ",
        "Bibirhat",
        "Bondor Tila",
        "Boropool",
        "Bow Bazar",
        "Boxirhat ",
        "Burischar ",
        "Burma Colony",
        "Cantonment ",
        "CDA Residential Area",
        "Cement Crossing",
        "CEPZ",
        "Chaitanna Goli",
        "Chaktai ",
        "Chandgaon",
        "Chandgaon R/A, Block A",
        "Chandgaon R/A, Block B ",
        "Chandrima",
        "Chasma Hill R/A",
        "Chatteswari Road",
        "Chawk Bazar ",
        "Chowdhury Para",
        "Chowmuhani",
        "Cinema Palace ",
        "City Gate",
        "CNB",
        "CNB Colony",
        "Colonel Hat",
        "Cosmopolitan R/A",
        "CRB Road ",
        "D.T. Road ",
        "Dakshin Kattali ",
        "Dampara",
        "Darogha Hat",
        "DC Road ",
        "Debar Par",
        "Dewan Bazar",
        "Dewanhat",
        "Double Mooring ",
        "Enayet Bazar ",
        "Farider Para ",
        "Fatehabad",
        "Firingi Bazar ",
        "Firoz Shah Colony ",
        "Free Port",
        "Gani Colony",
        "GEC Circle",
        "Gol Pahar Moor",
        "Halishahar",
        "Halishahar, Block A",
        "Halishahar, Block B",
        "Halishahar, Block G",
        "Halishahar, Block H",
        "Halishahar, Block I",
        "Halishahar, Block K",
        "Halishahar, Block L",
        "Hamjarbag ",
        "Hashem Bazar",
        "Hathazari",
        "Hazipara ",
        "Hill View R/A",
        "Ice Factory Road ",
        "Ishan Mistrir Hat",
        "Jalalabad H/S",
        "Jamal Khan ",
        "Jangalpara ",
        "Jhawtola",
        "Jubilee Road",
        "Kadamtali  ",
        "Kafco Housing colony",
        "Kalamia Bazar ",
        "Kalurghat",
        "Kamal Gate",
        "Kanon Dhara H/S",
        "Kapasgola",
        "Kaptai Rastar Matha",
        "Kata Pahar Lane",
        "Katalgonj R/A",
        "Kazir Dewri ",
        "Khatiber Hat",
        "Khulshi Colony",
        "Khulshi North",
        "Khulshi South",
        "Khulshi West",
        "Kotwali ",
        "Kulgaon",
        "Kunjachaya R/A",
        "Laldighir Par ",
        "Lalkhan Bazar",
        "Loharpool",
        "Love Lane",
        "M. A Aziz Road",
        "Madarbari East",
        "Madarbari West",
        "Majhir Ghat",
        "Mehedibag",
        "Mistripara",
        "Mohammad Nagar ",
        "Mohammadpur ",
        "Momin Bagh",
        "Momin Road",
        "Monsurabad",
        "Mosjid Goli",
        "Moti Jharna ",
        "Mousumi R/A",
        "Muradpur",
        "Nabi Nagar ",
        "Nalapara ",
        "Nandon Kanon",
        "Nasirabad",
        "Nasirabad H/S",
        "Nazir Para ",
        "Nazu Meah Hat",
        "New Market",
        "North Kattali",
        "O.R. Nizam Road",
        "Oxygen",
        "Pahartali",
        "Panchlaish R/A",
        "Patenga",
        "Pathantuli ",
        "Patharghata ",
        "Polytechnic",
        "Port Colony ",
        "Postarpar",
        "Probortok Circle",
        "Quaish",
        "Rahatarpul",
        "Rahman Nagar ",
        "Rose Valley R/A",
        "Ruby Gate ",
        "Sabujbag",
        "Sadarghat ",
        "Sagorika ",
        "Santibag R/A",
        "Saraipara",
        "Sat Rastar Matha ",
        "Shah Garibullah  H/S",
        "Shamoli R/A",
        "Sheikh Mujib Road",
        "Shershah Colony",
        "Sholokbahar",
        "Sholoshohor",
        "South Kattali",
        "Station Road",
        "Strand Road",
        "Sugandha R/A",
        "Surson Road",
        "Tankey Pahar ",
        "Tiger Pass",
        "Tin Puler Matha",
        "Urdo Road ",
        "Wapda Colony",
        "Zakir Hossain Road",
      ],
    },
    {
      name: "Khulna",
      locations: [
        "PTI More",
        "Toot Para",
        "Alam Nagar",
        "Alutala",
        "Baiti Para",
        "Banargati",
        "Banda",
        "Binoy Para",
        "BL College Area",
        "Bonik Para",
        "Boro Bazar",
        "Boro Khalpar",
        "Bosu Para",
        "Boyra",
        "BSCIC Industrial Area",
        "C&B Colony",
        "Choto Boyra",
        "Choto Khalpar",
        "Christian Colony",
        "Daroga Para",
        "Daspara",
        "Daulatpur",
        "Dharma Shava",
        "District Court",
        "Dokkhin Pabla",
        "Farazi Para",
        "Feri Ghat",
        "Fulbari Gate",
        "Gaikur",
        "Goborchaka",
        "Gollamari",
        "Golokdham",
        "Harinatala",
        "Helatala",
        "Hogladanga Bahsbaria",
        "Horintana",
        "Iqbal Nagar",
        "Islambag",
        "Jhardhanga",
        "Jinnah Para",
        "Jora Gate",
        "Jorakol Bazar",
        "K.D. Ghos Road",
        "Kalibari",
        "Kartik Kul",
        "KDA Avenue",
        "Khalishpur",
        "Khalishpur Bihari Colony",
        "Khan Jahan Ali Road",
        "Kholabaria",
        "Khulna Cantonment",
        "Khulna Medical Area",
        "Khulna University Area",
        "KMP Police Line",
        "Krishna Nagar",
        "KUET Area",
        "Labonchora",
        "Maheswarpasa",
        "Master Para",
        "Mathabhanga",
        "Mia Para",
        "Mirerdanga",
        "Mistri Para",
        "Mohammad Nagar",
        "Munshi Para",
        "Nabinagar",
        "Navi Gate",
        "Nazir Ghat",
        "Nirala Residential Area",
        "Nobo Polli",
        "Notun Rasta",
        "Pabla",
        "Paramanik Para",
        "Poi Para",
        "Poly Technical Area",
        "Rail Station Area",
        "Rasul Bag",
        "Rayer Mahal",
        "Religate",
        "Sanchibunia",
        "Sarkar Para",
        "Sheikh Para",
        "Shib Bari",
        "Shiromoni",
        "Sonadanga",
        "Sonadanga Moylapota",
        "SOS Shishu Polli",
        "Taltola",
        "Taltola Road",
        "Teligati",
        "Textile Mill",
        "Uttor Pabla",
      ],
    },
    {
      name: "Rajshahi",
      locations: [
        "Aam Chattar",
        "Aambagan",
        "Ashrayan Project",
        "Baharampur",
        "Basuri",
        "Binodpur",
        "Bornali Mor",
        "Boro Bongram",
        "Bosepara",
        "Budhpara",
        "Bullanpara",
        "Choto Bongram",
        "Chowddopai",
        "Court Station",
        "Daharampur",
        "Dashmari",
        "Dorga Para",
        "Haragram",
        "Hazrapukur",
        "Horogram",
        "Horogram Notunpara",
        "Kadirganj",
        "Katakhali",
        "Kathalbaria",
        "Kazla",
        "Khojapur",
        "Luxmipur Mor",
        "Meher Chandi ",
        "Methor Para",
        "Mirer Tek",
        "Mollapara",
        "Munshipara",
        "Nagar Para",
        "Nowdapara",
        "Padma Residential Area",
        "Raj Para",
        "Rajshahi University Area",
        "Rani Bazar",
        "Raypara",
        "RUET Area",
        "Sadhur Mor",
        "Sagarpara",
        "Salbagan",
        "Satbaria",
        "Shah Makhdum",
        "Shaheb Bazar",
        "Sheikpara",
        "Shilinda",
        "Shiroil Colony",
        "Sopura",
        "Sufi Nagar",
        "Sultanabad",
        "Terakhadia",
        "Thakurpara",
        "Tikapara",
        "Uposhohor",
        "Vata Para",
      ],
    },
    {
      name: "Sylhet",
      locations: [
        "Akhalia Bazar ",
        "Alampur",
        "Ambarkhana",
        "Badamura",
        "Baghbari",
        "Baluchor",
        "Bandar Bazar ",
        "Bankalapara ",
        "Barudkhana",
        "BGB Camp ",
        "Bhangatikar ",
        "Bhatalia ",
        "Bilpar ",
        "Cantonment",
        "Chalibandar ",
        "Chandmari Tila ",
        "Chowhatta Point ",
        "Chowkidekhi",
        "Daptari Para ",
        "Dariapara ",
        "Daudpur",
        "Dorshon Dewri",
        "Goaitola",
        "Golapbag ",
        "Hazart Shajalal Mazar Sharif ",
        "Hazrat Shah Paran Mazar Sharif",
        "Housing  Estate ",
        "Jail Road",
        "Jalalabad",
        "Jatarpur ",
        "Jharjhari Para ",
        "Kadamtoli ",
        "Kanishail ",
        "Karpara",
        "Kazi Tula",
        "Keya Para  ",
        "Khasdobir",
        "Khuliapara",
        "Khuliatula ",
        "Kolapara",
        "Kotwali ",
        "Kumar Para ",
        "Lakri Para ",
        "Lama Bazar",
        "Lama Para ",
        "Lamapara",
        "Machimpur ",
        "Majon Potti",
        "Majumder Para ",
        "Medical  Road",
        "Mira Bazar ",
        "Mira Para ",
        "Mirer Moydan",
        "Mollapara ",
        "Munshi Para ",
        "Naiorpul",
        "Nayapara",
        "Nayasarak",
        "Nehrai Para ",
        "Nowab Road ",
        "PathanTula",
        "Payra",
        "Police Line",
        "Raynagar",
        "Rikabi Bazar",
        "Sadar Para ",
        "Sadipara ",
        "Saodagar Tola ",
        "Sen Para ",
        "Shagordighirpar",
        "Shahi Eidgah ",
        "Shahjalal Upashahar A Block",
        "Shahjalal Upashahar B Block",
        "Shahjalal Upashahar C Block ",
        "Shahjalal Upashahar D Block ",
        "Shahjalal Upashahar E Block",
        "Shahjalal Upashahar F Block",
        "Shahjalal Upashahar G Block",
        "Shahjalal Upashahar H Block",
        "Shahjalal Upashahar I Block",
        "Shamimabad ",
        "Sheikh para ",
        "Sheikhghat",
        "Shibgonj",
        "Shuna Para",
        "Subhani Ghat",
        "Subid Bazar  ",
        "SUST Area  ",
        "Teli Para",
        "Telihaor ",
        "Tilagor",
        "Uposhohor",
        "West Ghasitula",
        "Western Pir",
        "Zindabazar Point ",
      ],
    },
    {
      name: "Barisal",
      locations: [
        "30 Godown",
        "Amanotgonj",
        "Amtolar Mor",
        "B.M College Masjid Gate",
        "Baklar Mor",
        "Bales Park",
        "Bazar Road",
        "Beltola",
        "Bibir Pukur Par",
        "Bogura Road",
        "Bot Tola",
        "Brown Compound",
        "Chandmari",
        "Choumatha",
        "Chowk Bazar",
        "College Avenue",
        "Feri Ghat",
        "Folpotti",
        "Gorosthan Road",
        "Hospital Road",
        "Ice Cream Factory Goli",
        "Jail Gate",
        "Jordan Road",
        "Kalizira",
        "Kashipur",
        "Kather Pool",
        "Kawnia",
        "Launch Ghat",
        "Mohabaj",
        "Muktijoddha Park",
        "Munsi Garez",
        "Natullabad",
        "Natun Bazar",
        "Oxford Mission Road",
        "Palashpur",
        "Police Line",
        "Port Road",
        "Ramakrishna Goli",
        "Rupatoli",
        "Rupatoli Housing",
        "Sadar Road",
        "Sagordi",
        "Shadhur Bat Tola",
        "Shoshan Ghat",
        "Sitla Khola",
        "Sonalir Mor",
        "Sreenath Chatterjee Lane",
        "Taltoli",
        "Vatar Khal",
        "Vatikhana",
        "Zero Point",
        "Zia Nagar",
      ],
    },
    {
      name: "Rangpur",
      locations: [
        "Adarsha Para",
        "Alamnagar",
        "Andhar Para",
        "Apon Para",
        "Attia Para",
        "Babu Khan",
        "Bajit Para",
        "Begum Rokeya University Area",
        "Bothla Para",
        "C.O Bazar",
        "Cantonment",
        "Chawak Bazar",
        "Chickli Park",
        "Cicular Road",
        "College Road",
        "Dangi Para",
        "Dewantuli",
        "Dhap",
        "Farm Road",
        "G L Roy Road",
        "Goneshpur",
        "Gunjon More",
        "Gupta Para",
        "Gurati Para",
        "Haffez Para",
        "Haji Para",
        "Haragach",
        "Honuman Tola",
        "Indira Moor",
        "Jolkar Moar",
        "Jumma Para",
        "Kamar Para",
        "Kerani Para",
        "Khorda",
        "Khotkhotia",
        "Koshaituli Road",
        "Kotki Para",
        "Kutir Para",
        "Lalbag",
        "Master Para",
        "Moddho Para",
        "Mulatol",
        "Munshi Para",
        "New Adarsha Para",
        "New Engineer Para",
        "Nilkantho",
        "Pakar Matha Road",
        "Pandar Dighi",
        "Pasari Para",
        "Pashuram",
        "Patbari",
        "Pirgachha",
        "Rahmat Para",
        "Santi Para",
        "Sardar Para",
        "Sen Para",
        "Silmon Road",
        "Sobuj Para",
        "Tajhat Road",
        "Tataipara",
        "Tin Matha",
        "Uttam Bania Para",
        "Uttam Hazi Para",
      ],
    },
    {
      name: "Cumilla",
      locations: [
        "Amtoli",
        "Ashok Tala",
        "Badur Tola",
        "Bagan Bari",
        "Bagichagaon",
        "Baropara",
        "Biswa Road",
        "BSCIC",
        "Chowk bazar",
        "Comilla Export Processing Zone",
        "Court Road",
        "Cumilla Cantonment",
        "Daulatpur",
        "DC Road",
        "Dhanmondi Road",
        "Dharmapur",
        "Dharmasagar Lake",
        "Dhulipara",
        "Digumbaritala",
        "Gobindapur",
        "Housing Estate",
        "Jangalia",
        "Jhakuni Para",
        "Jhautola",
        "Kaliajuri",
        "Kandirpar",
        "Kaptan Bazar",
        "Kotbari",
        "Kuchaituli",
        "Laksham Road",
        "Madina Masjid",
        "Manoharpur",
        "Mughal Toli",
        "Munsef Bari",
        "Nanua Dighir Par",
        "New Market",
        "North Chartha",
        "Nurpur",
        "Police Line",
        "Prince Road",
        "Race Course",
        "Rajgonj",
        "Ramghatla",
        "Ranir Bazar",
        "Ranir Dighir Par",
        "Second Muradpur",
        "Shaktola",
        "Shashongachha",
        "Shatora",
        "South Chartha",
        "Stadium Road",
        "Station Road",
        "Sujanagar",
        "Talpukur Par",
        "Thakur Para",
        "Tomsom Bridge",
        "Town Hall",
        "Ujir Dighirpar",
        "Uttara Residential Area",
        "Victoria College Road",
        "Wapda Colony",
        "Women's College Road",
        "Zilla School Road",
      ],
    },
    {
      name: "Gazipur",
      locations: [
        "B.I.D.C Bazar",
        "Board Bazar",
        "Boro Bari",
        "Boro Dewra",
        "Bypass",
        "Chandona Chowrasta",
        "Cherag Ali Market",
        "College Gate",
        "Dhirasram Bazar",
        "Ershad Nagar",
        "Gazipur Sadar Bazar",
        "Gazipura",
        "Harbaid Bazar",
        "Hossain Market",
        "Joydebpur",
        "Kashimpur Bazar",
        "Kodda Bazar",
        "Konabari Bazar",
        "Majukhan Bazar",
        "Maleker Bari",
        "Meghdubi Bazar",
        "Mil Bazar",
        "Mirer Bazar",
        "Mudafa",
        "National University Area",
        "Pubail Bazar",
        "Pubail College Gate",
        "Rajendrapur",
        "Sataish Bazar",
        "Shalna Bazar",
        "Shib Bari",
        "Shimultali",
        "Sign Board",
        "Station Road",
        "Takshal",
        "Tongi Bazar",
        "Vadun",
      ],
    },
    {
      name: "Narayanganj",
      locations: [
        "02 No. Rail Gate",
        "Amlapara",
        "B.B. Road",
        "Bandar",
        "Borofkol",
        "Burir Dokan",
        "Chanmari",
        "Chashara",
        "Chittagong Road",
        "College Road",
        "Deobhog",
        "DIT Road",
        "Don Chamber",
        "Esa Kha Road",
        "Fatullah",
        "Gabtoli",
        "Godnail",
        "Golachipa",
        "Gymkhana",
        "Jalkuri",
        "Jamtola Road",
        "Kali Bazar",
        "Khanpur",
        "Masdair Gorosthan",
        "Mission Para",
        "Mizmizi",
        "Nitaiganj",
        "Octo Office",
        "Pagla",
        "Paikpara",
        "Pathantuli",
        "Police Line",
        "Ponchoboti",
        "Rupayan Town",
        "Sabujbag",
        "Shahid Bappi Sarani Road",
        "Shitalakshya",
        "Siddhirganj",
        "Signboard",
        "T&T Colony",
        "Tamak Potti",
        "Ukil Para",
      ],
    },
    {
      name: "Mymensingh",
      locations: [
        "Ahammadabad",
        "Akua",
        "Alia Madrasa Road",
        "Amlapara",
        "Baghmara",
        "BAU Area",
        "Biddamoye School Area",
        "Boro Bazar",
        "Boundary Road",
        "Bramopolli",
        "Bypass More",
        "Cantonment",
        "Chamra Godam",
        "Choto Bazar",
        "Dhopakhola",
        "Durgabari",
        "Fulpur",
        "Ganginapar",
        "Golapjan Road",
        "Joynul Abedin Park",
        "Jubilee Road",
        "Kachari",
        "Kachi Jhuli Mor",
        "Kali Bari",
        "Kestopur",
        "Kewatkhali",
        "Lichu Bagan",
        "Maskanda",
        "Mintu College Area",
        "Nahar Road",
        "Natok Gol Lane",
        "Natun Bazar",
        "Naumahal",
        "Pat Godam",
        "Pocha Pukur Par",
        "Police Line",
        "Pondit Para",
        "Rail er Mor",
        "Sankipara",
        "Shehora",
        "Shema Choron Rai Road",
        "Shomvogonj",
        "Stadium Area",
        "Station Road",
        "Taltola",
        "Town Hall Mor",
        "Trishal Bus Stand",
        "Zilla More",
      ],
    },
  ],
  category: [
    "Bangla Medium",
    "English Medium",
    "English Version",
    "Arts",
    "Admission Test",
    "Test Preparation",
    "Religion Studies",
    "Skill Development",
    "Language Learning",
    "Special Child Education",
    "Uni Help",
    "Madrasa Medium",
  ],
  englishMediumClasses: [
    "Pre-Schooling",
    "Play",
    "Nursery",
    "KG",
    "Standard 1",
    "Standard 2",
    "Standard 3",
    "Standard 4",
    "Standard 5",
    "Standard 6",
    "Standard 7",
    "Standard 8",
    "Standard 9",
    "O Level",
    "A Level(AS)",
    "A Level(A2)",
  ],
  banglaMediumClasses: [
    "Pre-Scholling",
    "Play",
    "Nursery",
    "KG",
    "Class 1",
    "Class 2",
    "Class 3",
    "Class 4",
    "Class 5",
    "Class 6",
    "Class 7",
    "Class 8",
    "Class 9",
    "Class 10",
    "HSC 1st Year",
    "HSC 2nd Year",
  ],
  studentGender: ["male", "female"],
  tutorGender: ["male", "female", "any"],
  placeOfTuition: ["Student's Home", "My Home", "Online"],
};
