export const filterData = {
  tutoringStyles: [
    "One to One",
    "One to many",
    "Online Tutoring",
    "Shadow Tutoring ",
  ],
  tuitionType: [
    "Home Tutoring",
    "Online Tutoring",
    "Batch Tutoring",
    "Package Tutoring",
  ],
  daysPerWeek: [
    "1 Day",
    "2 Days",
    "3 Days",
    "4 Days",
    "5 Days",
    "6 Days",
    "7 Days",
  ],
  cityCorporations: [
    "Dhaka",
    "Savar",
    "Chattogram",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
    "Rangpur",
    "Cumilla",
    "Gazipur",
    "Narayanganj",
    "Mymensingh",
  ],
  cityCorporationWithLocation: [
    {
      name: "Dhaka",
      locations: [
        "Abdullahpur",
        "Adabor",
        "Aftabnagar",
        "Agargaon",
        "Airport Area ",
        "Arambagh",
        "Armanitola",
        "Asad Gate ",
        "Ashkona",
        "Azampur Kachabazar",
        "Azimpur",
        "Badda",
        "Baily Road",
        "Bakshi Bazar",
        "Banani",
        "Banani DOHS",
        "Banasree",
        "Bangla Motor",
        "Bangshal",
        "Baridhara",
        "Baridhara DOHS",
        "Bashabo",
        "Bashundhara R/A",
        "Bashundhara Riverview",
        "Baunia",
        "Begun Bari",
        "Bijoy Sarani",
        "Bijoynagar",
        "Bosila",
        "BUET Area",
        "Central Road ",
        "Chandrima Model Town",
        "Chawk Bazar",
        "College Gate",
        "Darussalam",
        "Daskhin Khan",
        "Demra",
        "Dhaka  Cantonment",
        "Dhaka Uddan Housing",
        "Dhaka University Area",
        "Dhanmondi",
        "Dholaikhal",
        "Dholaipar",
        "Diabari",
        "Dilkusha",
        "Dilu Road",
        "Doyagonj",
        "Eastern Housing",
        "ECB Chattar",
        "Elephant Road",
        "English Road",
        "Faidabad",
        "Faridabad",
        "Farmgate",
        "Fokirapul",
        "Gabtoli",
        "Gandaria",
        "Golapbag",
        "Gopibagh",
        "Goran",
        "Green Road",
        "Gulistan",
        "Gulshan-1",
        "Gulshan-2",
        "Hatirjheel",
        "Hatirpul",
        "Hazaribag",
        "Ibrahimpur",
        "Indira Road ",
        "Jatrabari",
        "Joynag Road",
        "Jurain ",
        "Kachukhet",
        "Kadamtoli",
        "Kafrul",
        "Kakrail",
        "Kalabagan",
        "Kalachandpur",
        "Kalshi",
        "Kamalapur",
        "Kamarpara",
        "Kamrangirchar",
        "Karwan Bazar",
        "Katabon",
        "Kathal Bagan",
        "Kawla",
        "Kazipara",
        "Kazla",
        "Keraniganj",
        "Khilgaon",
        "Khilkhet",
        "Kollanpur",
        "Kotwali",
        "Kuril",
        "Kurmitola",
        "Lake Circus Road",
        "Lalbag",
        "Lalmatia",
        "Luxmi Bazar",
        "Malibagh",
        "Manikdi",
        "Maniknagar",
        "Matikata",
        "Matuail",
        "Mirpur 1",
        "Mirpur 10",
        "Mirpur 11",
        "Mirpur 12",
        "Mirpur 13",
        "Mirpur 14",
        "Mirpur 2",
        "Mirpur 3",
        "Mirpur 6",
        "Mirpur 7",
        "Mirpur Cantonment",
        "Mirpur DOHS",
        "Mitford Road",
        "Mogbazar",
        "Mohakhali",
        "Mohakhali DOHS",
        "Mohammadpur",
        "Mollartek",
        "Monipur",
        "Monipuri Para",
        "Motijheel",
        "Mouchak",
        "Mugda",
        "Nakhalpara",
        "Nandipara",
        "Narinda",
        "Natun Bazar",
        "Nawabpur",
        "Naya Bazar",
        "Naya Paltan",
        "New Eskaton Road",
        "New Market",
        "Niketon",
        "Nikunja-1",
        "Nikunja-2",
        "Nilkhet",
        "Nobabgonj ",
        "Norda",
        "Paikpara",
        "Pallabi",
        "Paltan",
        "Panthapath",
        "Paribag",
        "Pilkhana",
        "Pink City Model Town",
        "Pirerbag",
        "Postogola",
        "Puran Dhaka",
        "Purana Paltan",
        "Ramna",
        "Rampura",
        "Ranavola",
        "Rayer Bazar",
        "Rayerbag",
        "Razarbagh",
        "Rupnagar",
        "Sabujbag",
        "Sadarghat",
        "Sankar",
        "Sayedabad",
        "Segunbagicha ",
        "Shahbag",
        "Shahinbag",
        "Shahjadpur",
        "Shajahanpur",
        "Shantibag",
        "Shantinagar",
        "Shekhertek",
        "Sher-e-Bangla Nagor",
        "Shewra",
        "Shewrapara",
        "Shyamoli",
        "Shyampur",
        "Siddeshwari",
        "Sobahan Bag",
        "Sonir Akra",
        "South Banasree",
        "Sukrabad",
        "Sutrapur",
        "Swamibagh",
        "Tejgaon",
        "Tejkunipara",
        "Tikatuli",
        "Tolarbag",
        "Turag",
        "Uttar Khan",
        "Uttara Sector 1",
        "Uttara Sector 10",
        "Uttara Sector 11",
        "Uttara Sector 12",
        "Uttara Sector 13",
        "Uttara Sector 14",
        "Uttara Sector 15",
        "Uttara Sector 16",
        "Uttara Sector 17",
        "Uttara Sector 18",
        "Uttara Sector 2",
        "Uttara Sector 3",
        "Uttara Sector 4",
        "Uttara Sector 5",
        "Uttara Sector 6",
        "Uttara Sector 7",
        "Uttara Sector 8",
        "Uttara Sector 9",
        "Vasantek",
        "Vatara",
        "Wari",
        "West Rampura",
        "Zigatola",
        "Zinzira",
      ],
    },
    {
      name: "Savar",
      locations: [
        "Thana Road",
        "20 Mile",
        "Anondopur",
        "Ashuliya",
        "Baipal",
        "Bank Colony",
        "Bank Town",
        "Bazar Road",
        "BEPZA",
        "Birulia Road",
        "C R P Road",
        "Cantonment",
        "Dendabor",
        "DEPZ",
        "Dhamrai",
        "East Bank Town",
        "Genda",
        "Jahangirnagar University Area",
        "Jamgora",
        "Kolma",
        "Majidpur",
        "Mousumi Market",
        "Nayarhat",
        "Nobinagar",
        "Norosinhopur",
        "Palli Bidyut",
        "Radio Colony",
        "Savar Bus Stand",
        "Savar DOHS",
        "Sobhanbag",
        "Soronika R/A",
        "Wapda Road",
        "West Bank Town",
        "Zirabo",
      ],
    },
    {
      name: "Chattogram",
      locations: [
        " New Mooring",
        "2 No. Gate",
        "A.K Khan",
        "Agrabad",
        "Agrabad Access Road",
        "Agrabad Barek Building",
        "Agrabad CDA R/A",
        "Agrabad Chowmuhani",
        "Akbarshah Railway Colony",
        "Ali Nagar",
        "Alkaran ",
        "Aman Bazar",
        "Amirbag",
        "Amtala",
        "Andarkilla",
        "Arakan H/S",
        "Arefin Nagar ",
        "Ashkar Dighir Par",
        "Aturar Depo",
        "Avay Mitra Ghat",
        "Badurtala",
        "Bahaddarhat",
        "Baitush Sharaf",
        "Bakalia East ",
        "Bakalia South",
        "Bakalia West ",
        "Baluchara",
        "Banani R/A",
        "Bandar",
        "Bangladesh Bank Colony",
        "Batali Road ",
        "Battery Goli",
        "Bayazid Bostami",
        "Bepari Para ",
        "Bibirhat",
        "Bondor Tila",
        "Boropool",
        "Bow Bazar",
        "Boxirhat ",
        "Burischar ",
        "Burma Colony",
        "Cantonment ",
        "CDA Residential Area",
        "Cement Crossing",
        "CEPZ",
        "Chaitanna Goli",
        "Chaktai ",
        "Chandgaon",
        "Chandgaon R/A, Block A",
        "Chandgaon R/A, Block B ",
        "Chandrima",
        "Chasma Hill R/A",
        "Chatteswari Road",
        "Chawk Bazar ",
        "Chowdhury Para",
        "Chowmuhani",
        "Cinema Palace ",
        "City Gate",
        "CNB",
        "CNB Colony",
        "Colonel Hat",
        "Cosmopolitan R/A",
        "CRB Road ",
        "D.T. Road ",
        "Dakshin Kattali ",
        "Dampara",
        "Darogha Hat",
        "DC Road ",
        "Debar Par",
        "Dewan Bazar",
        "Dewanhat",
        "Double Mooring ",
        "Enayet Bazar ",
        "Farider Para ",
        "Fatehabad",
        "Firingi Bazar ",
        "Firoz Shah Colony ",
        "Free Port",
        "Gani Colony",
        "GEC Circle",
        "Gol Pahar Moor",
        "Halishahar",
        "Halishahar, Block A",
        "Halishahar, Block B",
        "Halishahar, Block G",
        "Halishahar, Block H",
        "Halishahar, Block I",
        "Halishahar, Block K",
        "Halishahar, Block L",
        "Hamjarbag ",
        "Hashem Bazar",
        "Hathazari",
        "Hazipara ",
        "Hill View R/A",
        "Ice Factory Road ",
        "Ishan Mistrir Hat",
        "Jalalabad H/S",
        "Jamal Khan ",
        "Jangalpara ",
        "Jhawtola",
        "Jubilee Road",
        "Kadamtali  ",
        "Kafco Housing colony",
        "Kalamia Bazar ",
        "Kalurghat",
        "Kamal Gate",
        "Kanon Dhara H/S",
        "Kapasgola",
        "Kaptai Rastar Matha",
        "Kata Pahar Lane",
        "Katalgonj R/A",
        "Kazir Dewri ",
        "Khatiber Hat",
        "Khulshi Colony",
        "Khulshi North",
        "Khulshi South",
        "Khulshi West",
        "Kotwali ",
        "Kulgaon",
        "Kunjachaya R/A",
        "Laldighir Par ",
        "Lalkhan Bazar",
        "Loharpool",
        "Love Lane",
        "M. A Aziz Road",
        "Madarbari East",
        "Madarbari West",
        "Majhir Ghat",
        "Mehedibag",
        "Mistripara",
        "Mohammad Nagar ",
        "Mohammadpur ",
        "Momin Bagh",
        "Momin Road",
        "Monsurabad",
        "Mosjid Goli",
        "Moti Jharna ",
        "Mousumi R/A",
        "Muradpur",
        "Nabi Nagar ",
        "Nalapara ",
        "Nandon Kanon",
        "Nasirabad",
        "Nasirabad H/S",
        "Nazir Para ",
        "Nazu Meah Hat",
        "New Market",
        "North Kattali",
        "O.R. Nizam Road",
        "Oxygen",
        "Pahartali",
        "Panchlaish R/A",
        "Patenga",
        "Pathantuli ",
        "Patharghata ",
        "Polytechnic",
        "Port Colony ",
        "Postarpar",
        "Probortok Circle",
        "Quaish",
        "Rahatarpul",
        "Rahman Nagar ",
        "Rose Valley R/A",
        "Ruby Gate ",
        "Sabujbag",
        "Sadarghat ",
        "Sagorika ",
        "Santibag R/A",
        "Saraipara",
        "Sat Rastar Matha ",
        "Shah Garibullah  H/S",
        "Shamoli R/A",
        "Sheikh Mujib Road",
        "Shershah Colony",
        "Sholokbahar",
        "Sholoshohor",
        "South Kattali",
        "Station Road",
        "Strand Road",
        "Sugandha R/A",
        "Surson Road",
        "Tankey Pahar ",
        "Tiger Pass",
        "Tin Puler Matha",
        "Urdo Road ",
        "Wapda Colony",
        "Zakir Hossain Road",
      ],
    },
    {
      name: "Khulna",
      locations: [
        "PTI More",
        "Toot Para",
        "Alam Nagar",
        "Alutala",
        "Baiti Para",
        "Banargati",
        "Banda",
        "Binoy Para",
        "BL College Area",
        "Bonik Para",
        "Boro Bazar",
        "Boro Khalpar",
        "Bosu Para",
        "Boyra",
        "BSCIC Industrial Area",
        "C&B Colony",
        "Choto Boyra",
        "Choto Khalpar",
        "Christian Colony",
        "Daroga Para",
        "Daspara",
        "Daulatpur",
        "Dharma Shava",
        "District Court",
        "Dokkhin Pabla",
        "Farazi Para",
        "Feri Ghat",
        "Fulbari Gate",
        "Gaikur",
        "Goborchaka",
        "Gollamari",
        "Golokdham",
        "Harinatala",
        "Helatala",
        "Hogladanga Bahsbaria",
        "Horintana",
        "Iqbal Nagar",
        "Islambag",
        "Jhardhanga",
        "Jinnah Para",
        "Jora Gate",
        "Jorakol Bazar",
        "K.D. Ghos Road",
        "Kalibari",
        "Kartik Kul",
        "KDA Avenue",
        "Khalishpur",
        "Khalishpur Bihari Colony",
        "Khan Jahan Ali Road",
        "Kholabaria",
        "Khulna Cantonment",
        "Khulna Medical Area",
        "Khulna University Area",
        "KMP Police Line",
        "Krishna Nagar",
        "KUET Area",
        "Labonchora",
        "Maheswarpasa",
        "Master Para",
        "Mathabhanga",
        "Mia Para",
        "Mirerdanga",
        "Mistri Para",
        "Mohammad Nagar",
        "Munshi Para",
        "Nabinagar",
        "Navi Gate",
        "Nazir Ghat",
        "Nirala Residential Area",
        "Nobo Polli",
        "Notun Rasta",
        "Pabla",
        "Paramanik Para",
        "Poi Para",
        "Poly Technical Area",
        "Rail Station Area",
        "Rasul Bag",
        "Rayer Mahal",
        "Religate",
        "Sanchibunia",
        "Sarkar Para",
        "Sheikh Para",
        "Shib Bari",
        "Shiromoni",
        "Sonadanga",
        "Sonadanga Moylapota",
        "SOS Shishu Polli",
        "Taltola",
        "Taltola Road",
        "Teligati",
        "Textile Mill",
        "Uttor Pabla",
      ],
    },
    {
      name: "Rajshahi",
      locations: [
        "Aam Chattar",
        "Aambagan",
        "Ashrayan Project",
        "Baharampur",
        "Basuri",
        "Binodpur",
        "Bornali Mor",
        "Boro Bongram",
        "Bosepara",
        "Budhpara",
        "Bullanpara",
        "Choto Bongram",
        "Chowddopai",
        "Court Station",
        "Daharampur",
        "Dashmari",
        "Dorga Para",
        "Haragram",
        "Hazrapukur",
        "Horogram",
        "Horogram Notunpara",
        "Kadirganj",
        "Katakhali",
        "Kathalbaria",
        "Kazla",
        "Khojapur",
        "Luxmipur Mor",
        "Meher Chandi ",
        "Methor Para",
        "Mirer Tek",
        "Mollapara",
        "Munshipara",
        "Nagar Para",
        "Nowdapara",
        "Padma Residential Area",
        "Raj Para",
        "Rajshahi University Area",
        "Rani Bazar",
        "Raypara",
        "RUET Area",
        "Sadhur Mor",
        "Sagarpara",
        "Salbagan",
        "Satbaria",
        "Shah Makhdum",
        "Shaheb Bazar",
        "Sheikpara",
        "Shilinda",
        "Shiroil Colony",
        "Sopura",
        "Sufi Nagar",
        "Sultanabad",
        "Terakhadia",
        "Thakurpara",
        "Tikapara",
        "Uposhohor",
        "Vata Para",
      ],
    },
    {
      name: "Sylhet",
      locations: [
        "Akhalia Bazar ",
        "Alampur",
        "Ambarkhana",
        "Badamura",
        "Baghbari",
        "Baluchor",
        "Bandar Bazar ",
        "Bankalapara ",
        "Barudkhana",
        "BGB Camp ",
        "Bhangatikar ",
        "Bhatalia ",
        "Bilpar ",
        "Cantonment",
        "Chalibandar ",
        "Chandmari Tila ",
        "Chowhatta Point ",
        "Chowkidekhi",
        "Daptari Para ",
        "Dariapara ",
        "Daudpur",
        "Dorshon Dewri",
        "Goaitola",
        "Golapbag ",
        "Hazart Shajalal Mazar Sharif ",
        "Hazrat Shah Paran Mazar Sharif",
        "Housing  Estate ",
        "Jail Road",
        "Jalalabad",
        "Jatarpur ",
        "Jharjhari Para ",
        "Kadamtoli ",
        "Kanishail ",
        "Karpara",
        "Kazi Tula",
        "Keya Para  ",
        "Khasdobir",
        "Khuliapara",
        "Khuliatula ",
        "Kolapara",
        "Kotwali ",
        "Kumar Para ",
        "Lakri Para ",
        "Lama Bazar",
        "Lama Para ",
        "Lamapara",
        "Machimpur ",
        "Majon Potti",
        "Majumder Para ",
        "Medical  Road",
        "Mira Bazar ",
        "Mira Para ",
        "Mirer Moydan",
        "Mollapara ",
        "Munshi Para ",
        "Naiorpul",
        "Nayapara",
        "Nayasarak",
        "Nehrai Para ",
        "Nowab Road ",
        "PathanTula",
        "Payra",
        "Police Line",
        "Raynagar",
        "Rikabi Bazar",
        "Sadar Para ",
        "Sadipara ",
        "Saodagar Tola ",
        "Sen Para ",
        "Shagordighirpar",
        "Shahi Eidgah ",
        "Shahjalal Upashahar A Block",
        "Shahjalal Upashahar B Block",
        "Shahjalal Upashahar C Block ",
        "Shahjalal Upashahar D Block ",
        "Shahjalal Upashahar E Block",
        "Shahjalal Upashahar F Block",
        "Shahjalal Upashahar G Block",
        "Shahjalal Upashahar H Block",
        "Shahjalal Upashahar I Block",
        "Shamimabad ",
        "Sheikh para ",
        "Sheikhghat",
        "Shibgonj",
        "Shuna Para",
        "Subhani Ghat",
        "Subid Bazar  ",
        "SUST Area  ",
        "Teli Para",
        "Telihaor ",
        "Tilagor",
        "Uposhohor",
        "West Ghasitula",
        "Western Pir",
        "Zindabazar Point ",
      ],
    },
    {
      name: "Barisal",
      locations: [
        "30 Godown",
        "Amanotgonj",
        "Amtolar Mor",
        "B.M College Masjid Gate",
        "Baklar Mor",
        "Bales Park",
        "Bazar Road",
        "Beltola",
        "Bibir Pukur Par",
        "Bogura Road",
        "Bot Tola",
        "Brown Compound",
        "Chandmari",
        "Choumatha",
        "Chowk Bazar",
        "College Avenue",
        "Feri Ghat",
        "Folpotti",
        "Gorosthan Road",
        "Hospital Road",
        "Ice Cream Factory Goli",
        "Jail Gate",
        "Jordan Road",
        "Kalizira",
        "Kashipur",
        "Kather Pool",
        "Kawnia",
        "Launch Ghat",
        "Mohabaj",
        "Muktijoddha Park",
        "Munsi Garez",
        "Natullabad",
        "Natun Bazar",
        "Oxford Mission Road",
        "Palashpur",
        "Police Line",
        "Port Road",
        "Ramakrishna Goli",
        "Rupatoli",
        "Rupatoli Housing",
        "Sadar Road",
        "Sagordi",
        "Shadhur Bat Tola",
        "Shoshan Ghat",
        "Sitla Khola",
        "Sonalir Mor",
        "Sreenath Chatterjee Lane",
        "Taltoli",
        "Vatar Khal",
        "Vatikhana",
        "Zero Point",
        "Zia Nagar",
      ],
    },
    {
      name: "Rangpur",
      locations: [
        "Adarsha Para",
        "Alamnagar",
        "Andhar Para",
        "Apon Para",
        "Attia Para",
        "Babu Khan",
        "Bajit Para",
        "Begum Rokeya University Area",
        "Bothla Para",
        "C.O Bazar",
        "Cantonment",
        "Chawak Bazar",
        "Chickli Park",
        "Cicular Road",
        "College Road",
        "Dangi Para",
        "Dewantuli",
        "Dhap",
        "Farm Road",
        "G L Roy Road",
        "Goneshpur",
        "Gunjon More",
        "Gupta Para",
        "Gurati Para",
        "Haffez Para",
        "Haji Para",
        "Haragach",
        "Honuman Tola",
        "Indira Moor",
        "Jolkar Moar",
        "Jumma Para",
        "Kamar Para",
        "Kerani Para",
        "Khorda",
        "Khotkhotia",
        "Koshaituli Road",
        "Kotki Para",
        "Kutir Para",
        "Lalbag",
        "Master Para",
        "Moddho Para",
        "Mulatol",
        "Munshi Para",
        "New Adarsha Para",
        "New Engineer Para",
        "Nilkantho",
        "Pakar Matha Road",
        "Pandar Dighi",
        "Pasari Para",
        "Pashuram",
        "Patbari",
        "Pirgachha",
        "Rahmat Para",
        "Santi Para",
        "Sardar Para",
        "Sen Para",
        "Silmon Road",
        "Sobuj Para",
        "Tajhat Road",
        "Tataipara",
        "Tin Matha",
        "Uttam Bania Para",
        "Uttam Hazi Para",
      ],
    },
    {
      name: "Cumilla",
      locations: [
        "Amtoli",
        "Ashok Tala",
        "Badur Tola",
        "Bagan Bari",
        "Bagichagaon",
        "Baropara",
        "Biswa Road",
        "BSCIC",
        "Chowk bazar",
        "Comilla Export Processing Zone",
        "Court Road",
        "Cumilla Cantonment",
        "Daulatpur",
        "DC Road",
        "Dhanmondi Road",
        "Dharmapur",
        "Dharmasagar Lake",
        "Dhulipara",
        "Digumbaritala",
        "Gobindapur",
        "Housing Estate",
        "Jangalia",
        "Jhakuni Para",
        "Jhautola",
        "Kaliajuri",
        "Kandirpar",
        "Kaptan Bazar",
        "Kotbari",
        "Kuchaituli",
        "Laksham Road",
        "Madina Masjid",
        "Manoharpur",
        "Mughal Toli",
        "Munsef Bari",
        "Nanua Dighir Par",
        "New Market",
        "North Chartha",
        "Nurpur",
        "Police Line",
        "Prince Road",
        "Race Course",
        "Rajgonj",
        "Ramghatla",
        "Ranir Bazar",
        "Ranir Dighir Par",
        "Second Muradpur",
        "Shaktola",
        "Shashongachha",
        "Shatora",
        "South Chartha",
        "Stadium Road",
        "Station Road",
        "Sujanagar",
        "Talpukur Par",
        "Thakur Para",
        "Tomsom Bridge",
        "Town Hall",
        "Ujir Dighirpar",
        "Uttara Residential Area",
        "Victoria College Road",
        "Wapda Colony",
        "Women's College Road",
        "Zilla School Road",
      ],
    },
    {
      name: "Gazipur",
      locations: [
        "B.I.D.C Bazar",
        "Board Bazar",
        "Boro Bari",
        "Boro Dewra",
        "Bypass",
        "Chandona Chowrasta",
        "Cherag Ali Market",
        "College Gate",
        "Dhirasram Bazar",
        "Ershad Nagar",
        "Gazipur Sadar Bazar",
        "Gazipura",
        "Harbaid Bazar",
        "Hossain Market",
        "Joydebpur",
        "Kashimpur Bazar",
        "Kodda Bazar",
        "Konabari Bazar",
        "Majukhan Bazar",
        "Maleker Bari",
        "Meghdubi Bazar",
        "Mil Bazar",
        "Mirer Bazar",
        "Mudafa",
        "National University Area",
        "Pubail Bazar",
        "Pubail College Gate",
        "Rajendrapur",
        "Sataish Bazar",
        "Shalna Bazar",
        "Shib Bari",
        "Shimultali",
        "Sign Board",
        "Station Road",
        "Takshal",
        "Tongi Bazar",
        "Vadun",
      ],
    },
    {
      name: "Narayanganj",
      locations: [
        "02 No. Rail Gate",
        "Amlapara",
        "B.B. Road",
        "Bandar",
        "Borofkol",
        "Burir Dokan",
        "Chanmari",
        "Chashara",
        "Chittagong Road",
        "College Road",
        "Deobhog",
        "DIT Road",
        "Don Chamber",
        "Esa Kha Road",
        "Fatullah",
        "Gabtoli",
        "Godnail",
        "Golachipa",
        "Gymkhana",
        "Jalkuri",
        "Jamtola Road",
        "Kali Bazar",
        "Khanpur",
        "Masdair Gorosthan",
        "Mission Para",
        "Mizmizi",
        "Nitaiganj",
        "Octo Office",
        "Pagla",
        "Paikpara",
        "Pathantuli",
        "Police Line",
        "Ponchoboti",
        "Rupayan Town",
        "Sabujbag",
        "Shahid Bappi Sarani Road",
        "Shitalakshya",
        "Siddhirganj",
        "Signboard",
        "T&T Colony",
        "Tamak Potti",
        "Ukil Para",
      ],
    },
    {
      name: "Mymensingh",
      locations: [
        "Ahammadabad",
        "Akua",
        "Alia Madrasa Road",
        "Amlapara",
        "Baghmara",
        "BAU Area",
        "Biddamoye School Area",
        "Boro Bazar",
        "Boundary Road",
        "Bramopolli",
        "Bypass More",
        "Cantonment",
        "Chamra Godam",
        "Choto Bazar",
        "Dhopakhola",
        "Durgabari",
        "Fulpur",
        "Ganginapar",
        "Golapjan Road",
        "Joynul Abedin Park",
        "Jubilee Road",
        "Kachari",
        "Kachi Jhuli Mor",
        "Kali Bari",
        "Kestopur",
        "Kewatkhali",
        "Lichu Bagan",
        "Maskanda",
        "Mintu College Area",
        "Nahar Road",
        "Natok Gol Lane",
        "Natun Bazar",
        "Naumahal",
        "Pat Godam",
        "Pocha Pukur Par",
        "Police Line",
        "Pondit Para",
        "Rail er Mor",
        "Sankipara",
        "Shehora",
        "Shema Choron Rai Road",
        "Shomvogonj",
        "Stadium Area",
        "Station Road",
        "Taltola",
        "Town Hall Mor",
        "Trishal Bus Stand",
        "Zilla More",
      ],
    },
  ],
  category: [
    "Bangla Medium",
    "English Medium",
    "English Version",
    "Madrasa Medium",
    "Arts",
    "Admission Test",
    "Test Preparation",
    "Religious Studies",
    "Professional Skill Development",
    "Special Skill Development",
    "Language Learning",
    // "Special Child Education",
    // "Uni Help",
  ],
  tutoringCatalog: [
    // English Medium
    {
      id: "english_medium",
      category: "English Medium",
      classes: [
        // ---------- PRE-SCHOOLING / PLAY / NURSERY / KG ----------
        {
          id: "pre_schooling_play_nursery_kg",
          name: "Pre-Schooling / Play / Nursery / KG (Class / Course)",
          subjects: ["All", "Bangla", "English", "Math", "Islamic Studies"],
        },

        // ---------- STANDARD 1–3 ----------
        {
          id: "standard_1_2_3",
          name: "Standard 1/ Standard 2/ Standard 3 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
          ],
        },

        // ---------- STANDARD 4 ----------
        {
          id: "standard_4",
          name: "Standard 4 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh & Global Studies",
            "Social Science",
          ],
        },

        // ---------- STANDARD 5 ----------
        {
          id: "standard_5",
          name: "Standard 5 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "English Literature",
            "Science",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh & Global Studies",
            "Social Science",
          ],
        },

        // ---------- STANDARD 6 ----------
        {
          id: "standard_6",
          name: "Standard 6 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "English Literature",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Drawing",
            "Bangladesh & Global Studies",
            "Social Science",
          ],
        },

        // ---------- STANDARD 7 ----------
        {
          id: "standard_7",
          name: "Standard 7 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math",
            "English Literature",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh & Global Studies",
            "Social Science",
          ],
        },

        // ---------- STANDARD 8 ----------
        {
          id: "standard_8",
          name: "Standard 8 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math B",
            "Additional Maths",
            "English Literature",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Commerce",
            "Maths",
            "Accounting",
            "Social Studies",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh & Global Studies",
            "Social Science",
          ],
        },

        // ---------- STANDARD 9 ----------
        {
          id: "standard_9",
          name: "Standard 9 (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math B",
            "Additional Maths",
            "English Literature",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Commerce",
            "Maths",
            "Accounting",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh Studies",
            "Social Science",
          ],
        },

        // ---------- O LEVEL ----------
        {
          id: "o_level",
          name: "O level (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Math B",
            "Additional Maths",
            "English Literature",
            "English Language",
            "Maths D",
            "Science",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Commerce",
            "Maths",
            "Accounting",
            "ICT",
            "History",
            "Geography",
            "Islamic Studies",
            "Bangladesh Studies",
            "Social Science",
            "Law",
            "Environmental Management",
          ],
        },

        // ---------- A LEVEL (AS) ----------
        {
          id: "a_level_as",
          name: "A Level (AS) (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Additional Maths",
            "English Literature",
            "English Language",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Commerce",
            "Maths",
            "Accounting",
            "ICT",
            "History",
            "Geography",
            "Bangladesh Studies",
            "Law",
            "Sociology",
            "Psychology",
            "Environmental System & Societies",
            "Politics",
            "Computer Science",
            "Finance",
            "Statistics",
            "Mechanics",
            "Marine Science",
          ],
        },

        // ---------- A LEVEL (A2) ----------
        {
          id: "a_level_a2",
          name: "A Level (A2) (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Additional Maths",
            "English Literature",
            "English Language",
            "Physics",
            "Chemistry",
            "Biology",
            "Economics",
            "Business Studies",
            "Commerce",
            "Maths",
            "Accounting",
            "ICT",
            "History",
            "Geography",
            "Bangladesh Studies",
            "Law",
            "Sociology",
            "Psychology",
            "Environmental System & Societies",
            "Politics",
            "Computer Science",
            "Finance",
            "Statistics",
            "Mechanics",
            "Marine Science",
          ],
        },
      ],
    },
    // English Version
    {
      id: "english_version",
      category: "English Version",
      classes: [
        // ---------- PRE-SCHOOLING ----------
        {
          id: "pre_scholling",
          name: "Pre-Scholling",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "play",
          name: "Play",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "kg",
          name: "KG",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },

        // ---------- PRIMARY (CLASS 1–5) ----------
        {
          id: "class_1",
          name: "Class 1",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_2",
          name: "Class 2",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_3",
          name: "Class 3",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_4",
          name: "Class 4",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_5",
          name: "Class 5",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },

        // ---------- HIGH SCHOOL (CLASS 6–8) ----------
        {
          id: "class_6",
          name: "Class 6",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },
        {
          id: "class_7",
          name: "Class 7",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },
        {
          id: "class_8",
          name: "Class 8",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },

        // ---------- CLASS 9 ----------
        {
          id: "class_9",
          name: "Class 9",
          subjects: [
            "Geography",
            "History",
            "Business Enterpreneurship",
            "Agricultural Education",
            "Bangladesh & Global Studies",
            "Home Economics",
            "Physical Education",
            "ICT",
            "General Science",
            "Dinance & Banking",
            "Biology",
            "Civics",
            "Physology",
            "All",
            "Managamanet",
            "Economics",
            "Social Science",
            "Religious Studies",
            "Accounting",
            "English",
            "Bangla",
            "Higher Math",
            "General Math",
            "Chemistry",
            "Physics",
          ],
        },

        // ---------- CLASS 10 (same as class 9) ----------
        {
          id: "class_10",
          name: "Class 10",
          subjects: [
            "Geography",
            "History",
            "Business Enterpreneurship",
            "Agricultural Education",
            "Bangladesh & Global Studies",
            "Home Economics",
            "Physical Education",
            "ICT",
            "General Science",
            "Dinance & Banking",
            "Biology",
            "Civics",
            "Physology",
            "All",
            "Managamanet",
            "Economics",
            "Social Science",
            "Religious Studies",
            "Accounting",
            "English",
            "Bangla",
            "Higher Math",
            "General Math",
            "Chemistry",
            "Physics",
          ],
        },

        // ---------- HSC 1st YEAR ----------
        {
          id: "hsc_1st_year",
          name: "HSC 1st Year",
          subjects: [
            "English",
            "Political Science",
            "History",
            "Islamic History and Culture",
            "Social Work",
            "Logic",
            "Agricultural Education",
            "Higher Maths",
            "Production Management & Marketing",
            "Commercial Geography",
            "Economics",
            "Sociology",
            "Statistics",
            "Religious Studies",
            "Psychology",
            "Geography",
            "Civics",
            "Management",
            "ICT",
            "Finance",
            "Accounting",
            "Biology",
            "Chemistry",
            "Physics",
            "Bangla",
            "All",
            "Engineering Drawing",
          ],
        },

        // ---------- HSC 2nd YEAR ----------
        {
          id: "hsc_2nd_year",
          name: "HSC 2nd Year",
          subjects: [
            "Physics",
            "Political Science",
            "History",
            "Islamic History and Culture",
            "Social Work",
            "Psychology",
            "Logic",
            "Agricultural Education",
            "Production Management & Marketing",
            "Commercial Geography",
            "English",
            "Sociology",
            "Statistics",
            "Religious Studies",
            "Psychology",
            "Geography",
            "Civics",
            "Economics",
            "Management",
            "Bangla",
            "Finance",
            "Accounting",
            "Business Studies",
            "ICT",
            "Biology",
            "Higher Maths",
            "Chemistry",
            "All",
            "Engineering Drawing",
          ],
        },
      ],
    },
    // Bangla Medium
    {
      id: "bangla_medium",
      category: "Bangla Medium",
      classes: [
        // ---------- PRE-SCHOOLING ----------
        {
          id: "pre_scholling",
          name: "Pre-Scholling",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "play",
          name: "Play",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "nursery",
          name: "Nursery",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },
        {
          id: "kg",
          name: "KG",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
          ],
        },

        // ---------- PRIMARY (CLASS 1–5) ----------
        {
          id: "class_1",
          name: "Class 1",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_2",
          name: "Class 2",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_3",
          name: "Class 3",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_4",
          name: "Class 4",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },
        {
          id: "class_5",
          name: "Class 5",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
          ],
        },

        // ---------- HIGH SCHOOL (CLASS 6–8) ----------
        {
          id: "class_6",
          name: "Class 6",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },
        {
          id: "class_7",
          name: "Class 7",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },
        {
          id: "class_8",
          name: "Class 8",
          subjects: [
            "All",
            "English",
            "Bangla",
            "General Math",
            "Religious Studies",
            "General Science",
            "Social Science",
            "Drawing",
            "Others",
            "Geography",
            "History",
            "Art & Crafts",
            "Agricultural Education",
            "ICT",
            "Bangladesh & Global Studies",
          ],
        },

        // ---------- CLASS 9 ----------
        {
          id: "class_9",
          name: "Class 9",
          subjects: [
            "Geography",
            "History",
            "Business Enterpreneurship",
            "Agricultural Education",
            "Bangladesh & Global Studies",
            "Home Economics",
            "Physical Education",
            "ICT",
            "General Science",
            "Dinance & Banking",
            "Biology",
            "Civics",
            "Physology",
            "All",
            "Managamanet",
            "Economics",
            "Social Science",
            "Religious Studies",
            "Accounting",
            "English",
            "Bangla",
            "Higher Math",
            "General Math",
            "Chemistry",
            "Physics",
          ],
        },

        // ---------- CLASS 10 (same as class 9) ----------
        {
          id: "class_10",
          name: "Class 10",
          subjects: [
            "Geography",
            "History",
            "Business Enterpreneurship",
            "Agricultural Education",
            "Bangladesh & Global Studies",
            "Home Economics",
            "Physical Education",
            "ICT",
            "General Science",
            "Dinance & Banking",
            "Biology",
            "Civics",
            "Physology",
            "All",
            "Managamanet",
            "Economics",
            "Social Science",
            "Religious Studies",
            "Accounting",
            "English",
            "Bangla",
            "Higher Math",
            "General Math",
            "Chemistry",
            "Physics",
          ],
        },

        // ---------- HSC 1st YEAR ----------
        {
          id: "hsc_1st_year",
          name: "HSC 1st Year",
          subjects: [
            "English",
            "Political Science",
            "History",
            "Islamic History and Culture",
            "Social Work",
            "Logic",
            "Agricultural Education",
            "Higher Maths",
            "Production Management & Marketing",
            "Commercial Geography",
            "Economics",
            "Sociology",
            "Statistics",
            "Religious Studies",
            "Psychology",
            "Geography",
            "Civics",
            "Management",
            "ICT",
            "Finance",
            "Accounting",
            "Biology",
            "Chemistry",
            "Physics",
            "Bangla",
            "All",
            "Engineering Drawing",
          ],
        },

        // ---------- HSC 2nd YEAR ----------
        {
          id: "hsc_2nd_year",
          name: "HSC 2nd Year",
          subjects: [
            "Physics",
            "Political Science",
            "History",
            "Islamic History and Culture",
            "Social Work",
            "Psychology",
            "Logic",
            "Agricultural Education",
            "Production Management & Marketing",
            "Commercial Geography",
            "English",
            "Sociology",
            "Statistics",
            "Religious Studies",
            "Psychology",
            "Geography",
            "Civics",
            "Economics",
            "Management",
            "Bangla",
            "Finance",
            "Accounting",
            "Business Studies",
            "ICT",
            "Biology",
            "Higher Maths",
            "Chemistry",
            "All",
            "Engineering Drawing",
          ],
        },
      ],
    },
    // Madrasa Medium
    {
      id: "madrasa_medium",
      category: "Madrasa Medium",
      classes: [
        // ---------- PLAY ----------
        {
          id: "play",
          name: "Play (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- NURSERY ----------
        {
          id: "nursery",
          name: "Nursery (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 1 ----------
        {
          id: "class_1",
          name: "Class 1 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 2 ----------
        {
          id: "class_2",
          name: "Class 2 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 3 ----------
        {
          id: "class_3",
          name: "Class 3 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 4 ----------
        {
          id: "class_4",
          name: "Class 4 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 5 ----------
        {
          id: "class_5",
          name: "Class 5 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "General Science",
            "Islamic Studies",
            "Other",
          ],
        },

        // ---------- CLASS 6 ----------
        {
          id: "class_6",
          name: "Class 6 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "ICT",
            "Other",
          ],
        },

        // ---------- CLASS 7 ----------
        {
          id: "class_7",
          name: "Class 7 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "ICT",
            "Geography & Environment",
            "Other",
          ],
        },

        // ---------- CLASS 8 ----------
        {
          id: "class_8",
          name: "Class 8 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "ICT",
            "Bangladesh & Global Studies",
            "Other",
          ],
        },

        // ---------- CLASS 9 ----------
        {
          id: "class_9",
          name: "Class 9 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "ICT",
            "Bangladesh & Global Studies",
            "Other",
          ],
        },

        // ---------- CLASS 10 ----------
        {
          id: "class_10",
          name: "Class 10 (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Science",
            "Islamic Studies",
            "ICT",
            "Bangladesh & Global Studies",
            "Other",
          ],
        },

        // ---------- ALIM 1ST YEAR ----------
        {
          id: "alim_1st_year",
          name: "Alim 1st Year (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Quran & Hadith",
            "Fiqh",
            "Aqaid & Faraid",
            "ICT",
            "Other",
          ],
        },

        // ---------- ALIM 2ND YEAR ----------
        {
          id: "alim_2nd_year",
          name: "Alim 2nd Year (Class / Course)",
          subjects: [
            "All",
            "Arabic",
            "Bangla",
            "English",
            "Math",
            "Quran & Hadith",
            "Fiqh",
            "Aqaid & Faraid",
            "ICT",
            "Other",
          ],
        },
      ],
    },
    // Religious Studies:
    {
      id: "religious_studies",
      category: "Religious Studies",
      classes: [
        // ---------- ISLAMIC STUDIES ----------
        {
          id: "islamic_studies",
          name: "Islamic Studies (Class / Course)",
          subjects: [
            "Quran for Beginner",
            "Quran for Adult",
            "Learning Salat",
            "Hifzul Quran",
          ],
        },

        // ---------- HINDUISM STUDIES ----------
        {
          id: "hinduism_studies",
          name: "Hinduism Studies (Class / Course)",
          subjects: [
            "Shri Bhagavad Gita for Beginner",
            "Shri Bhagavad Gita for Adult",
          ],
        },

        // ---------- BUDDHISM STUDIES ----------
        {
          id: "buddhism_studies",
          name: "Buddhism Studies (Class / Course)",
          subjects: ["Tripitaka for Beginner", "Tripitaka for Adult"],
        },

        // ---------- CHRISTIANITY STUDIES ----------
        {
          id: "christianity_studies",
          name: "Christianity Studies (Class / Course)",
          subjects: ["Bible for Beginner", "Bible for Adult"],
        },
      ],
    },
    // Admission Test
    {
      id: "admission_test",
      category: "Admission Test",
      classes: [
        // ---------- PUBLIC UNIVERSITY ----------
        {
          id: "public_university_admission_test",
          name: "Public University Admission Test (Class / Course)",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Maths",
            "Chemistry",
            "Biology",
            "Accounting",
            "Management",
            "Marketing",
            "Business Principles",
            "Business Entrepreneurship",
            "Economics",
            "Civics",
            "Analytical Skills",
            "Finance & Banking",
            "General Knowledge",
          ],
        },

        // ---------- PRIVATE UNIVERSITY ----------
        {
          id: "private_university_admission_test",
          name: "Private University Admission Test (Class / Course)",
          subjects: [
            "Bangla",
            "English",
            "ICT",
            "Physics",
            "Maths",
            "Chemistry",
            "Biology",
            "Accounting",
            "Management",
            "Analytical Skills",
            "Finance",
            "General Knowledge",
          ],
        },

        // ---------- MEDICAL COLLEGE ----------
        {
          id: "medical_college_admission_test",
          name: "Medical College Admission Test (Class / Course)",
          subjects: [
            "English",
            "Physics",
            "Chemistry",
            "Biology",
            "General Knowledge",
          ],
        },

        // ---------- ENGINEERING UNIVERSITY ----------
        {
          id: "engineering_university_admission_test",
          name: "Engineering University Admission Test (Class / Course)",
          subjects: [
            "Math",
            "Physics",
            "Chemistry",
            "English",
            "General Knowledge",
          ],
        },

        // ---------- SCHOOL ADMISSION TEST ----------
        {
          id: "school_admission_test",
          name: "School Admission Test (Class / Course)",
          subjects: [
            "All",
            "Bangla",
            "English",
            "Maths",
            "General Science",
            "Social Science",
            "Islamic Studies",
            "Geography",
            "General Knowledge",
          ],
        },
      ],
    },
    // Arts
    {
      id: "arts",
      category: "Arts",
      classes: [
        // ---------- DRAWING & PAINTING ----------
        {
          id: "drawing_and_painting",
          name: "Drawing & Painting (Class / Course)",
          subjects: ["line Drawing", "Sketch", "Water Color", "Oil Painting"],
        },

        // ---------- HANDWRITTING ----------
        {
          id: "handwritting",
          name: "Handwritting (Class / Course)",
          subjects: [
            "Bangla Handwritting",
            "English Handwritting",
            "Arabic Handwritting",
            "Chinese Handwritting",
            "korean Handwritting",
            "Russain Handwritting",
            "German Handwritting",
            "French Handwritting",
            "Spanish Handwritting",
          ],
        },

        // ---------- MUSIC ----------
        {
          id: "music",
          name: "Music (Class / Course)",
          subjects: [
            "Music for Beginner",
            "Islamic Sangeet",
            "Deshattobodhok Gaan",
            "Folk Sangeet",
            "Nazrul Sangeet",
            "Rabindra Sangeet",
            "Adhunik Sangeet",
            "Uchango Sangeet",
            "Shastriya Sangeet",
            "Polli Giti",
          ],
        },

        // ---------- INSTRUMENTAL MUSIC ----------
        {
          id: "instrumental_music",
          name: "Instrumental Music (Class / Course)",
          subjects: [
            "Tabla",
            "Guitar",
            "Harmonium",
            "Ukulele",
            "Clarinet",
            "Silver Flute",
            "Mridanga",
            "Drums",
            "Keyboard",
            "Mandolin",
            "Saxophone",
            "Dotara",
            "Sitar",
            "Flute",
            "Violin",
            "Piano",
            "Behala",
          ],
        },

        // ---------- DANCE ----------
        {
          id: "dance",
          name: "Dance (Class / Course)",
          subjects: [
            "Classical Dance",
            "Folk Dance",
            "Modern Dance",
            "Western Dance",
            "Belly Dance",
            "Kathak Dance",
          ],
        },

        // ---------- CRAFTING ----------
        {
          id: "crafting",
          name: "Crafting (Class / Course)",
          subjects: [
            "Paper Crafts",
            "Flower Crafts",
            "Fiber & Textile Crafts",
            "Ceramics & Glass Crafts",
            "Needlework",
            "Leather Work",
          ],
        },
      ],
    },
    // Language Learning
    {
      id: "language_learning",
      category: "Language Learning",
      classes: [
        // ---------- ENGLISH ----------
        {
          id: "english_language",
          name: "English (Class / Course)",
          subjects: ["English Language learning", "Business Communication"],
        },

        // ---------- ARABIC ----------
        {
          id: "arabic_language",
          name: "Arabic (Class / Course)",
          subjects: ["Arabic Language learning"],
        },

        // ---------- JAPANESE ----------
        {
          id: "japanese_language",
          name: "Japanese (Class / Course)",
          subjects: ["Japanese Language learning"],
        },

        // ---------- TURKISH ----------
        {
          id: "turkish_language",
          name: "Turkish (Class / Course)",
          subjects: ["Turkish Language learning"],
        },

        // ---------- GERMAN ----------
        {
          id: "german_language",
          name: "German (Class / Course)",
          subjects: ["German Language learning"],
        },

        // ---------- FRENCH ----------
        {
          id: "french_language",
          name: "French (Class / Course)",
          subjects: ["French Language learning"],
        },

        // ---------- SPANISH ----------
        {
          id: "spanish_language",
          name: "Spanish (Class / Course)",
          subjects: ["Spanish Language learning"],
        },

        // ---------- CHINESE ----------
        {
          id: "chinese_language",
          name: "Chinese (Class / Course)",
          subjects: ["Chinese Language learning"],
        },

        // ---------- KOREAN ----------
        {
          id: "korean_language",
          name: "Korean (Class / Course)",
          subjects: ["Korean Language learning"],
        },

        // ---------- BANGLA ----------
        {
          id: "bangla_language",
          name: "Bangla (Class / Course)",
          subjects: ["Bangla Language learning"],
        },

        // ---------- RUSSIAN ----------
        {
          id: "russian_language",
          name: "Russian (Class / Course)",
          subjects: ["Russian Language learning"],
        },
      ],
    },
    // Test Preparation
    {
      id: "test_preparation",
      category: "Test Preparation",
      classes: [
        // ---------- IELTS ----------
        {
          id: "ielts",
          name: "IELTS (Class / Course)",
          subjects: ["Speaking", "Listening", "Reading", "Writing"],
        },

        // ---------- TOEFL ----------
        {
          id: "toefl",
          name: "TOEFL (Class / Course)",
          subjects: ["Speaking", "Listening", "Reading", "Writing"],
        },

        // ---------- GMAT ----------
        {
          id: "gmat",
          name: "GMAT (Class / Course)",
          subjects: [
            "Analytical Writing Assessment",
            "Integrated Reasoning",
            "Quantitative",
            "Verbal",
          ],
        },

        // ---------- GRE ----------
        {
          id: "gre",
          name: "GRE (Class / Course)",
          subjects: [
            "Analytical Writing",
            "Verbal Reasoning",
            "Quantitative Reasoning",
          ],
        },

        // ---------- GED ----------
        {
          id: "ged",
          name: "GED (Class / Course)",
          subjects: [
            "Science",
            "Math",
            "Social Studies",
            "Language Writing",
            "Language Reading",
          ],
        },

        // ---------- SAT ----------
        {
          id: "sat",
          name: "SAT (Class / Course)",
          subjects: ["Math", "Writing", "Critical Reading"],
        },
      ],
    },
    // Professional Skill Development
    {
      id: "professional_skill_development",
      category: "Professional Skill Development",
      classes: [
        // ---------- WEB DESIGN ----------
        {
          id: "web_design",
          name: "Web Design (Class / Course)",
          subjects: [
            "Website Logo",
            "Website Template",
            "Website Banner & Slider",
          ],
        },

        // ---------- WEB DEVELOPMENT ----------
        {
          id: "web_development",
          name: "Web Development (Class / Course)",
          subjects: [
            "CSS",
            "HTML",
            "BDMS",
            "CMS",
            "NET",
            "JavaScipt",
            "Python",
            "Perl",
          ],
        },

        // ---------- COMPUTER PROGRAMMING ----------
        {
          id: "computer_programming",
          name: "Computer Programming (Class / Course)",
          subjects: [
            "Java",
            "Python",
            "C",
            "C++",
            "React",
            "PHP",
            "Ruby",
            "Matlab",
          ],
        },

        // ---------- ADOBE ILLUSTRATOR ----------
        {
          id: "adobe_illustrator",
          name: "Adobe Illustrator (Class / Course)",
          subjects: [
            "Adobe Illustrator in Basic Level",
            "Adobe Illustrator in Advanced Level",
          ],
        },

        // ---------- ADOBE PHOTOSHOP ----------
        {
          id: "adobe_photoshop",
          name: "Adobe Photoshop (Class / Course)",
          subjects: [
            "Adobe Photoshop in Basic Level",
            "Adobe Photoshop in Advanced Level",
          ],
        },

        // ---------- MICROSOFT OFFICE ----------
        {
          id: "microsoft_office",
          name: "Microsoft Office (Class / Course)",
          subjects: [
            "Microsoft Office Word",
            "Microsoft Office Access",
            "Microsoft Office Excel",
            "Microsoft Office Power Point",
          ],
        },

        // ---------- VIDEO EDITING ----------
        {
          id: "video_editing",
          name: "Video Editing (Class / Course)",
          subjects: [
            "Video Editing in Basic Level",
            "Video Editing in Advanced Level",
          ],
        },

        // ---------- FASHION DESIGN ----------
        {
          id: "fashion_design",
          name: "Fashion Design (Class / Course)",
          subjects: [
            "Fashion Design in Basic Level",
            "Fashion Design in Advanced Level",
          ],
        },

        // ---------- FASHION DRAWING ----------
        {
          id: "fashion_drawing",
          name: "Fashion Drawing (Class / Course)",
          subjects: ["Elements of Design", "Illustration-1", "Illustration-2"],
        },

        // ---------- DIGITAL MARKETING ----------
        {
          id: "digital_marketing",
          name: "Digital Marketing (Class / Course)",
          subjects: [
            "Search Engine Optimization (SEO)",
            "Search Engine Marketing (SEM)",
            "Web Analytics",
            "Content Creation",
            "Social Media Marketing (SMM)",
            "Mobile Marketing",
            "Email Marketing",
            "Interactive Marketing",
            "Affiliate Marketing",
          ],
        },

        // ---------- SEWING & TAILORING ----------
        {
          id: "sewing_and_tailoring",
          name: "Sewing & Tailoring (Class / Course)",
          subjects: ["Cutting", "Sewing", "Embroidery", "Printmaking"],
        },
      ],
    },
    // Special Skill Development
    {
      id: "special_skill_development",
      category: "Special Skill Development",
      classes: [
        // ---------- PHOTOGRAPHY ----------
        {
          id: "photography",
          name: "Photography (Class / Course)",
          subjects: ["Photography Primary Level", "Photography Advanced Level"],
        },

        // ---------- COOKING ----------
        {
          id: "cooking",
          name: "Cooking (Class / Course)",
          subjects: [
            "Bangla Food",
            "Thai Food",
            "Chinese Food",
            "Bakery",
            "Pastry",
          ],
        },

        // ---------- YOGA ----------
        {
          id: "yoga",
          name: "Yoga (Class / Course)",
          subjects: ["Yoga - Beginner Level", "Yoga - Advanced Level"],
        },

        // ---------- GYM ----------
        {
          id: "gym",
          name: "Gym (Class / Course)",
          subjects: ["Gym - Beginner Level", "Gym - Advanced Level"],
        },

        // ---------- DRIVING / RIDING ----------
        {
          id: "driving_riding",
          name: "Driving/ Riding (Class / Course)",
          subjects: [
            "Car Driving - Beginner Level",
            "Car Driving - Intermediate Level",
            "Bike Riding - Beginner Level",
            "Bike Riding - Intermediate Level",
            "Scooty Riding - Beginner Level",
            "Scooty Riding - Intermediate Level",
          ],
        },

        // ---------- KARATE ----------
        {
          id: "karate",
          name: "Karate (Class / Course)",
          subjects: ["Karate for Beginners", "Karate for Self Defense"],
        },
      ],
    },
  ],
  studentGender: ["male", "female"],
  tutorGender: ["male", "female", "any"],
  placeOfTuition: ["Student's Home", "My Home", "Online"],
};
